# Generated by Django 5.0.9 on 2026-09-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="baseline_captured_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
