# Generated by Django 5.0.9 on 2026-09-01 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_members_through"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_template",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="CustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Texte"),
                            ("number", "Nombre"),
                            ("date", "Date"),
                            ("select", "Liste de choix"),
                            ("checkbox", "Case a cocher"),
                            ("url", "Lien"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("options", models.JSONField(blank=True, default=list)),
                ("order", models.PositiveIntegerField(default=0)),
                ("show_in_list", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_fields",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("project", "name")},
            },
        ),
    ]
