# Generated by Django 5.0.9 on 2026-09-01 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_project_is_template_customfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("task_created", "Tache creee"),
                            ("column_changed", "Deplacee dans une colonne"),
                            ("task_completed", "Tache terminee (100%)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("move_to_column", "Deplacer vers une colonne"),
                            ("set_priority", "Changer la priorite"),
                            ("add_label", "Ajouter une etiquette"),
                            ("notify_assignees", "Notifier les assignes"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action_priority", models.CharField(blank=True, max_length=10)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "action_column",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="projects.boardcolumn",
                    ),
                ),
                (
                    "action_label",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="projects.label",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_rules",
                        to="projects.project",
                    ),
                ),
                (
                    "trigger_column",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="projects.boardcolumn",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
