# Generated by Django 5.0.9 on 2026-09-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_automationrule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Brouillon"),
                    ("active", "En cours"),
                    ("on_hold", "En pause"),
                    ("done", "Termine"),
                    ("archived", "Archive"),
                ],
                default="planned",
                max_length=10,
            ),
        ),
    ]
