# Generated by Django 5.0.9 on 2026-09-07 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_alter_project_status"),
        ("tasks", "0008_attachment_reviewed_at_attachment_reviewed_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customfield",
            name="excluded_tasks",
            field=models.ManyToManyField(
                blank=True, related_name="excluded_custom_fields", to="tasks.task"
            ),
        ),
        migrations.AddField(
            model_name="customfield",
            name="level",
            field=models.CharField(
                choices=[("task", "Tache"), ("project", "Projet")],
                default="task",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ProjectCustomFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_values",
                        to="projects.customfield",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_values",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("field", "project")},
            },
        ),
    ]
