# Generated by Django 5.0.9 on 2026-09-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_customfield_excluded_tasks_customfield_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Texte"),
                    ("number", "Nombre"),
                    ("date", "Date"),
                    ("select", "Liste de choix"),
                    ("checkbox", "Case a cocher"),
                    ("switch", "Interrupteur (Oui/Non)"),
                    ("url", "Lien"),
                ],
                default="text",
                max_length=10,
            ),
        ),
    ]
