# Generated by Django 5.0.9 on 2026-09-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_actual_end_date_task_actual_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskdependency",
            name="enforce_blocking",
            field=models.BooleanField(default=False),
        ),
    ]
