# Generated by Django 5.0.9 on 2026-09-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_taskdependency_enforce_blocking"),
        ("workspaces", "0002_externalcontact"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="external_assignees",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_tasks",
                to="workspaces.externalcontact",
            ),
        ),
    ]
