# Generated by Django 5.0.9 on 2026-09-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_customfieldvalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="recurrence",
            field=models.CharField(
                choices=[
                    ("none", "Aucune"),
                    ("daily", "Quotidienne"),
                    ("weekly", "Hebdomadaire"),
                    ("monthly", "Mensuelle"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
